---
title: "Sim_for_Johan"
author: "Michel Nivard"
format: html
editor: visual
---

## 

First se draw snp effects

```{r}
library(MASS)

# get positive beta's

msnp <- 10000
means <- c(0,0)
Sigma <- matrix(c(1,.4,.4,1),2,2)

pos <- mvrnorm(msnp,means,Sigma)

cor(pos)
msnp_n <- 10000
means_n <- c(0,0)
Sigma_n <- matrix(c(1,-.3,-.3,1),2,2)
neg <- mvrnorm(msnp_n,means_n,Sigma_n)

cor(neg)

head(neg)



### TRUE GENOEM WIDE GENETIC CORRELATIONS:
true_rg <- cor(rbind(pos,neg))

```

Then in GCTA sim with 100% h2 (we make our own e2), see for code [HERE](https://yanglab.westlake.edu.cn/software/gcta/#GWASSimulation47)

```{bash}
# Simulate a quantitative trait with the heritability of 0.5 for a subset of individuals for 1 times
gcta64  --bfile test1  --simu-qt  --simu-causal-loci causal.snplist  --simu-hsq 1 --simu-rep 1  --keep test.indi.list --out test1

gcta64  --bfile test2  --simu-qt  --simu-causal-loci causal.snplist  --simu-hsq 1 --simu-rep 1  --keep test.indi.list --out test2

```

Make the environment:

```{r}

library(MASS)

# get environments

n_indi <- 30000 # replace with ypur real N!
means <- c(0,0)
Sigma <- matrix(c(1,.4,.4,1),2,2)

e <- mvrnorm(msnp,means,Sigma)


G1 <- read.table("test1.phen")
G2 <- read.table("test2.phen")


write.table("test1_final.phen",c(G1[,1:2],G1[,3] + e[,1]))
write.table("test2_final.phen",c(G2[,1:2],G2[,3] + e[,2]))


```

Do the GWAS

```{bash}

# To run a linear regression analysis using fastGWA
gcta64 --bfile test1_final --fastGWA-lr --pheno phenotype.txt --qcovar pc.txt --covar fixed.txt --thread-num 10 --out geno_assoc



# To run a linear regression analysis using fastGWA
gcta64 --bfile test2_final  --fastGWA-lr --pheno phenotype.txt --qcovar pc.txt --covar fixed.txt --thread-num 10 --out geno_assoc
```

do ldsc!
